config/routes.rb
Rails.application.routes.draw do
  resources :forum_posts
  resources :forum_threads, only: [:show]
  devise_for :users

  root to: "forum_threads#index"

end

app/models/forum_post.rb
class ForumPost < ActiveRecord::Base
	belongs_to :user
	belongs_to :forum_thread
end

app/models/forum_thread.rb
class ForumThread < ActiveRecord::Base
	belongs_to :user
	has_many :forum_posts

	

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :forum_threads
  has_many :forum_posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/forum_posts_controller.rb
class ForumPostsController < ApplicationController
  before_action :set_forum_post, only: [:show, :edit, :update, :destroy]

  # GET /forum_posts
  # GET /forum_posts.json
  def index
    @forum_posts = ForumPost.all
  end

  # GET /forum_posts/1
  # GET /forum_posts/1.json
  def show
  end

  # GET /forum_posts/new
  def new
    @forum_post = ForumPost.new
  end

  # GET /forum_posts/1/edit
  def edit
  end

  # POST /forum_posts
  # POST /forum_posts.json
  def create
    @forum_post = ForumPost.new(forum_post_params)

    respond_to do |format|
      if @forum_post.save
        format.html { redirect_to @forum_post, notice: 'Forum post was successfully created.' }
        format.json { render :show, status: :created, location: @forum_post }
      else
        format.html { render :new }
        format.json { render json: @forum_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forum_posts/1
  # PATCH/PUT /forum_posts/1.json
  def update
    respond_to do |format|
      if @forum_post.update(forum_post_params)
        format.html { redirect_to @forum_post, notice: 'Forum post was successfully updated.' }
        format.json { render :show, status: :ok, location: @forum_post }
      else
        format.html { render :edit }
        format.json { render json: @forum_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forum_posts/1
  # DELETE /forum_posts/1.json
  def destroy
    @forum_post.destroy
    respond_to do |format|
      format.html { redirect_to forum_posts_url, notice: 'Forum post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forum_post
      @forum_post = ForumPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forum_post_params
      params.require(:forum_post).permit(:content, :forum_thread_id, :user_id)
    end
end

app/controllers/forum_threads_controller.rb
class ForumThreadsController < ApplicationController
  before_action :set_forum_thread, only: [:show, :edit, :update, :destroy]
  
  # GET /forum_threads
  # GET /forum_threads.json
  def index
    @forum_threads = ForumThread.all
    
  end

  # GET /forum_threads/1
  # GET /forum_threads/1.json
  def show
    id = params[:id]
    @forum_thread = ForumThread.find(id)
    #@comment = @forum_thread.forum_posts.all

  end

  # GET /forum_threads/new
  def new
    @forum_thread = ForumThread.new
  end

  # GET /forum_threads/1/edit
  def edit
  end

  # POST /forum_threads
  # POST /forum_threads.json
  def create
    @forum_thread = ForumThread.new(forum_thread_params)

    respond_to do |format|
      if @forum_thread.save
        format.html { redirect_to @forum_thread, notice: 'Forum thread was successfully created.' }
        format.json { render :show, status: :created, location: @forum_thread }
      else
        format.html { render :new }
        format.json { render json: @forum_thread.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forum_threads/1
  # PATCH/PUT /forum_threads/1.json
  def update
    respond_to do |format|
      if @forum_thread.update(forum_thread_params)
        format.html { redirect_to @forum_thread, notice: 'Forum thread was successfully updated.' }
        format.json { render :show, status: :ok, location: @forum_thread }
      else
        format.html { render :edit }
        format.json { render json: @forum_thread.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forum_threads/1
  # DELETE /forum_threads/1.json
  def destroy
    @forum_thread.destroy
    respond_to do |format|
      format.html { redirect_to forum_threads_url, notice: 'Forum thread was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forum_thread
      @forum_thread = ForumThread.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forum_thread_params
      params.require(:forum_thread).permit(:title, :content, :sticky_order, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forum_posts_helper.rb
module ForumPostsHelper
end

app/helpers/forum_threads_helper.rb
module ForumThreadsHelper
end

app/helpers/home_controller_helper.rb
module HomeControllerHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/forum_posts/_form.html.erb
<%= form_for(@forum_post) do |f| %>
  <% if @forum_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forum_post.errors.count, "error") %> prohibited this forum_post from being saved:</h2>

      <ul>
      <% @forum_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :forum_thread_id %><br>
    <%= f.number_field :forum_thread_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forum_posts/edit.html.erb
<h1>Editing Forum Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @forum_post %> |
<%= link_to 'Back', forum_posts_path %>

app/views/forum_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Forum Posts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Forum thread</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @forum_posts.each do |forum_post| %>
      <tr>
        <td><%= forum_post.content %></td>
        <td><%= forum_post.forum_thread_id %></td>
        <td><%= forum_post.user_id %></td>
        <td><%= link_to 'Show', forum_post %></td>
        <td><%= link_to 'Edit', edit_forum_post_path(forum_post) %></td>
        <td><%= link_to 'Destroy', forum_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Forum post', new_forum_post_path %>

app/views/forum_posts/new.html.erb
<h1>New Forum Post</h1>

<%= render 'form' %>

<%= link_to 'Back', forum_posts_path %>

app/views/forum_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @forum_post.content %>
</p>

<p>
  <strong>Forum thread:</strong>
  <%= @forum_post.forum_thread_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @forum_post.user_id %>
</p>

<%= link_to 'Edit', edit_forum_post_path(@forum_post) %> |
<%= link_to 'Back', forum_posts_path %>

app/views/forum_threads/_form.html.erb
<%= form_for(@forum_thread) do |f| %>
  <% if @forum_thread.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forum_thread.errors.count, "error") %> prohibited this forum_thread from being saved:</h2>

      <ul>
      <% @forum_thread.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :sticky_order %><br>
    <%= f.number_field :sticky_order %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forum_threads/edit.html.erb
<h1>Editing Forum Thread</h1>

<%= render 'form' %>

<%= link_to 'Show', @forum_thread %> |
<%= link_to 'Back', forum_threads_path %>

app/views/forum_threads/index.html.erb
<div class="row"> <!-- row class bootstrap -->
  <div class="col-md-6 col-md-offset-3">
  <!-- col itu column md itu tipe layar 6 itu ukuran panjang nya  -->
  <!-- col md offset 3 ada tambahan samping kanan dan kiri jadi 3663  -->

  <!-- untuk search -->
  <% @forum_threads.each do |thread| %>

<!-- salah disini -->
    <div class="thread">
      <h3><%#= link_to thread.title.titleize, forum_thread_path(thread) %></h3><!-- #titlelize syntax rails untuk judul agar huruf besar di depan -->
      <h3><%= link_to thread.title.titleize, forum_thread_path(thread) %></h3>

      <div class="date">
        <%= thread.created_at %> oleh <%= thread.user.name %>
        <!-- strftime untuk mengganti format date -->
      </div>
      <div class="content">
        <%= thread.content %>
      </div>
      <div class="comment">
        <%= thread.forum_posts.count %> comment
      </div>

      <div style="clear: both;"></div>
    </div>

    <% end %>
  </div>
</div>

app/views/forum_threads/new.html.erb
<h1>New Forum Thread</h1>

<%= render 'form' %>

<%= link_to 'Back', forum_threads_path %>

app/views/forum_threads/show.html.erb
<div class="row"> <!-- row class bootstrap -->
  <div class="col-md-6 col-md-offset-3">
  <!-- col itu column md itu tipe layar 6 itu ukuran panjang nya  -->
  <!-- col md offset 3 ada tambahan samping kanan dan kiri jadi 3663  -->

  <!-- untuk search -->


<!-- salah disini -->
    <div class="thread">
      <h3><%#= link_to thread.title.titleize, forum_thread_path(thread) %></h3><!-- #titlelize syntax rails untuk judul agar huruf besar di depan -->
      <h3><%= @forum_thread.title.titleize %></h3>

      <div class="date">
        <%= @forum_thread.created_at %> oleh <%= @forum_thread.user.name %>
        <!-- strftime untuk mengganti format date -->
      </div>
      <div class="content">
        <%= @forum_thread.content %>
      </div>
     

      <div style="clear: both;"></div>
    </div>

    <% if @forum_thread.forum_posts.any? %>
    <!-- apakah ada post di thread? -->
        <% @forum_thread.forum_posts.each do |post| %>
        <div class="thread">
          <div class="date">
            <%= post.created_at %> oleh <%= post.user.name %>
          </div>
          <div class="content">
            <%= post.content %>
          </div>

        </div>
      <% end %>
    <% else %>
    <div>
      jadilah yang pertama comment
    </div>
      
    <% end %>
    
      
    

    
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Miniapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/navbar' %>
<div class="container">
  <%= yield %>
</div>


</body>
</html>